/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.sql.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rey
 */
public class interfa extends javax.swing.JFrame {
    BufferedReader leer= new BufferedReader
				(new InputStreamReader (System.in));

    private int factura;

    /**
     * Creates new form interfa
     */
    public interfa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPanelmenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldconsulta2 = new javax.swing.JTextField();
        jButtonsalir = new javax.swing.JButton();
        jButtonc2 = new javax.swing.JButton();
        jTextFieldconsulta1 = new javax.swing.JTextField();
        jButtonc1 = new javax.swing.JButton();
        jLabellogo = new javax.swing.JLabel();
        jLabelfondo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonsalir2 = new javax.swing.JButton();
        jLabellogo2 = new javax.swing.JLabel();
        jScrollPanetexto = new javax.swing.JScrollPane();
        jTextAreaconsulta = new javax.swing.JTextArea();
        jButtonconsulta = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabelfondo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonsalir1 = new javax.swing.JButton();
        jLabellogo1 = new javax.swing.JLabel();
        menu1 = new javax.swing.JButton();
        CONSULTA2 = new javax.swing.JButton();
        pro5 = new javax.swing.JTextField();
        pro3 = new javax.swing.JTextField();
        pro6 = new javax.swing.JTextField();
        pro4 = new javax.swing.JTextField();
        pro7 = new javax.swing.JTextField();
        pro2 = new javax.swing.JTextField();
        pro1 = new javax.swing.JTextField();
        jLabelfondo3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/herramientas1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1200, 450));
        setMinimumSize(new java.awt.Dimension(1200, 450));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1325, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldconsulta2.setBackground(new java.awt.Color(204, 51, 0));
        jTextFieldconsulta2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextFieldconsulta2.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldconsulta2.setText("consulta 2");
        jTextFieldconsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldconsulta2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldconsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 200, 60));

        jButtonsalir.setBackground(new java.awt.Color(102, 0, 0));
        jButtonsalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonsalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsalir.setText("salir");
        jButtonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(907, 20, 80, 40));

        jButtonc2.setBackground(new java.awt.Color(51, 0, 0));
        jButtonc2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonc2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonc2.setText("clic");
        jButtonc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonc2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, 50));

        jTextFieldconsulta1.setBackground(new java.awt.Color(204, 51, 0));
        jTextFieldconsulta1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextFieldconsulta1.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldconsulta1.setText("consulta 1");
        jTextFieldconsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldconsulta1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldconsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, 60));

        jButtonc1.setBackground(new java.awt.Color(51, 0, 0));
        jButtonc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonc1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonc1.setText("clic");
        jButtonc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonc1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, 50));

        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/logo.png"))); // NOI18N
        jPanel1.add(jLabellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 590, 150));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/965a3d95a2a778b9103a20c7e1d77862.jpg"))); // NOI18N
        jPanel1.add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1315, 339));

        jTabbedPanelmenu.addTab("menu", jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(1325, 350));
        jPanel3.setMinimumSize(new java.awt.Dimension(1325, 350));
        jPanel3.setPreferredSize(new java.awt.Dimension(1325, 350));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonsalir2.setBackground(new java.awt.Color(153, 51, 0));
        jButtonsalir2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonsalir2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsalir2.setText("salir");
        jButtonsalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalir2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonsalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 80, 40));

        jLabellogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/logo.png"))); // NOI18N
        jPanel3.add(jLabellogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 590, 150));

        jTextAreaconsulta.setBackground(new java.awt.Color(102, 51, 0));
        jTextAreaconsulta.setColumns(20);
        jTextAreaconsulta.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextAreaconsulta.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaconsulta.setRows(5);
        jScrollPanetexto.setViewportView(jTextAreaconsulta);

        jPanel3.add(jScrollPanetexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 910, 50));

        jButtonconsulta.setText("consultar");
        jButtonconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonconsultaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        menu.setBackground(new java.awt.Color(153, 51, 0));
        menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelfondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/arriere-plan-bois-panneaux-muraux-145641466140z.jpg"))); // NOI18N
        jPanel3.add(jLabelfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -30, 1000, 350));

        jTabbedPanelmenu.addTab("consulta1", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonsalir1.setBackground(new java.awt.Color(255, 153, 51));
        jButtonsalir1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonsalir1.setText("salir");
        jButtonsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsalir1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonsalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 80, 40));

        jLabellogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/logo.png"))); // NOI18N
        jPanel2.add(jLabellogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 590, 150));

        menu1.setBackground(new java.awt.Color(255, 153, 51));
        menu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu1.setText("menu");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel2.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 40));

        CONSULTA2.setBackground(new java.awt.Color(255, 153, 51));
        CONSULTA2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CONSULTA2.setText("CONSULTAR PRODUCTOS");
        CONSULTA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTA2ActionPerformed(evt);
            }
        });
        jPanel2.add(CONSULTA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 40));

        pro5.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 420, -1));

        pro3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 420, -1));

        pro6.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 420, -1));

        pro4.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 420, -1));

        pro7.setBackground(new java.awt.Color(255, 153, 51));
        pro7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pro7.setText("codigo        nombre          precio        cantidad          importe");
        pro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro7ActionPerformed(evt);
            }
        });
        jPanel2.add(pro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 420, -1));

        pro2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 420, -1));

        pro1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.add(pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 420, -1));

        jLabelfondo3.setBackground(new java.awt.Color(102, 51, 0));
        jLabelfondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenproyec/herramientas1.png"))); // NOI18N
        jPanel2.add(jLabelfondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, -1));

        jTabbedPanelmenu.addTab("consulta2", jPanel2);
        jTabbedPanelmenu.addTab("tab4", jTabbedPane1);

        getContentPane().add(jTabbedPanelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonsalirActionPerformed

    private void jTextFieldconsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldconsulta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldconsulta2ActionPerformed

    private void jButtonc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonc1ActionPerformed
      jTabbedPanelmenu.setSelectedIndex(2);
    }//GEN-LAST:event_jButtonc1ActionPerformed

    private void jTextFieldconsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldconsulta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldconsulta1ActionPerformed

    private void jButtonc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonc2ActionPerformed
      jTabbedPanelmenu.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonc2ActionPerformed

    private void jButtonsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalir1ActionPerformed
  System.exit(0);
    }//GEN-LAST:event_jButtonsalir1ActionPerformed

    private void jButtonsalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsalir2ActionPerformed
  System.exit(0);
    }//GEN-LAST:event_jButtonsalir2ActionPerformed

    private void jButtonconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonconsultaActionPerformed
         
          try{
            Connection miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/basee","root","");
            Statement miStatement= miConexion.createStatement();
			PreparedStatement sentencia=miConexion.prepareStatement("select cliente.nombre, cliente.A_P,cliente.A_M,cliente.cod_cliente, factura.fecha_fac, factura.sub_total, factura.iva, factura.total_neto\n" +
"from factura, cliente\n" +
"where cliente.cod_cliente=factura.cod_cliente and factura.cod_factura=?  ;");
			// ESTABLECER LOS PARAMETROS
			int numero1 = Integer.parseInt( JOptionPane.showInputDialog(null,"Introduzca un numero de factura ","consulta",JOptionPane.QUESTION_MESSAGE) );
                        
			sentencia.setInt(1, numero1);
			//sentencia.setString(2, "Miranda");
			ResultSet rs=sentencia.executeQuery();
                        if(rs!=null)
                             jTextAreaconsulta.setText("vacio, no esxite");
			while (rs.next()) {

                                         jTextAreaconsulta.setText(rs.getString(1) + " |\t" + rs.getString(2)+" |\t"+ rs.getString(3)+" |\t"+ rs.getInt(4) +" |\t"+ rs.getDate(5)+" |\t"+rs.getInt(6) +" |\t"+ rs.getDouble(7) +" |\t"+ rs.getDouble(8));
                        }
                        rs.close(); 
                        }
        catch(Exception e){
            //System.out.println("no funciona :C :v");
            e.printStackTrace();
        }
        /*String hola;
        hola = "hola";
        jTextAreaconsulta.setText(hola);*/
    }//GEN-LAST:event_jButtonconsultaActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
            jTabbedPanelmenu.setSelectedIndex(0);
    }//GEN-LAST:event_menuActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
            jTabbedPanelmenu.setSelectedIndex(0);
    }//GEN-LAST:event_menu1ActionPerformed

    private void CONSULTA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTA2ActionPerformed
        try{
         //   Connection miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/basee","root","");
            Statement miStatement= miConexion.createStatement();
			PreparedStatement sentencia=miConexion.prepareStatement("select producto.cod_producto, producto.producto, producto.precio_producto, detalle_factura.cantida, detalle_factura.importe\n" +
"from producto, detalle_factura, cliente, factura \n" +
"where cliente.cod_cliente=factura.cod_cliente and factura.cod_factura=detalle_factura.cod_factura and detalle_factura.cod_produccion=producto.cod_producto and factura.cod_factura=?;");
			// ESTABLECER LOS PARAMETROS
                        int con=0;
			int PRODUCTO = Integer.parseInt( JOptionPane.showInputDialog(
        null,"Introduzca un numero de factura ",
        "consulta",
        JOptionPane.QUESTION_MESSAGE) );
                        
			sentencia.setInt(1, PRODUCTO);
			//sentencia.setString(2, "Miranda");
			ResultSet rs=sentencia.executeQuery();
                        if(rs!=null)
                             pro1.setText("vacio no esxite");
			while (rs.next()) {
                            con++;
                            switch(con){
                             case 1:pro1.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;
                             case 2:pro2.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;
                             case 3:pro3.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;
                             case 4:pro4.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;
                             case 5:pro5.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;
                             case 6:pro6.setText(rs.getInt(1) + " \t" + rs.getString(2)+" \t"+ rs.getDouble(3)+" \t"+ rs.getInt(4) +" \t"+ rs.getDouble(5)+"\n"); break;

                            }
                        }
                        rs.close(); 
                        }
        catch(Exception e){
            //System.out.println("no funciona :C :v");
            e.printStackTrace();
        }
    }//GEN-LAST:event_CONSULTA2ActionPerformed

    private void pro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro7ActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new interfa().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONSULTA2;
    private javax.swing.JButton jButtonc1;
    private javax.swing.JButton jButtonc2;
    private javax.swing.JButton jButtonconsulta;
    private javax.swing.JButton jButtonsalir;
    private javax.swing.JButton jButtonsalir1;
    private javax.swing.JButton jButtonsalir2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JLabel jLabelfondo2;
    private javax.swing.JLabel jLabelfondo3;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabellogo1;
    private javax.swing.JLabel jLabellogo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPanetexto;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPanelmenu;
    private javax.swing.JTextArea jTextAreaconsulta;
    private javax.swing.JTextField jTextFieldconsulta1;
    private javax.swing.JTextField jTextFieldconsulta2;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    private javax.swing.JTextField pro1;
    private javax.swing.JTextField pro2;
    private javax.swing.JTextField pro3;
    private javax.swing.JTextField pro4;
    private javax.swing.JTextField pro5;
    private javax.swing.JTextField pro6;
    private javax.swing.JTextField pro7;
    // End of variables declaration//GEN-END:variables
}
